export interface Car {
    make: string;
    model: string;
    gender: string;
    buyerAge: number;
    country: string;
    city: string;
    dealerLatitude: number;
    dealerLongitude: number;
    colour: string;
    new: boolean;
    purchaseDate: Date;
    price: number;
    topSpeed: number;
}

export const testCars: Car[] = [
    {
        make: "Suzuki",
        model: "Vitara",
        gender: "Female",
        buyerAge: 51,
        country: "Belgium",
        city: "Antwerpen",
        dealerLatitude: 51.2472392,
        dealerLongitude: 4.4403455,
        colour: "Yellow",
        new: false,
        purchaseDate: new Date("2009-07-19"),
        price: 54806.14,
        topSpeed: 200.9,
    },
    {
        make: "Honda",
        model: "S2000",
        gender: "Male",
        buyerAge: 30,
        country: "China",
        city: "Jinhu",
        dealerLatitude: 33.025433,
        dealerLongitude: 119.020584,
        colour: "Crimson",
        new: false,
        purchaseDate: new Date("2015-10-26"),
        price: 51826.3,
        topSpeed: 158.5,
    },
    {
        make: "Toyota",
        model: "Previa",
        gender: "Female",
        buyerAge: 67,
        country: "Brazil",
        city: "Freguesia do Ribeirao da Ilha",
        dealerLatitude: -27.7203552,
        dealerLongitude: -48.563999,
        colour: "Violet",
        new: true,
        purchaseDate: new Date("2004-03-02"),
        price: 82844.12,
        topSpeed: 135.4,
    },
    {
        make: "Lamborghini",
        model: "Diablo",
        gender: "Male",
        buyerAge: 38,
        country: "Mexico",
        city: "Providencia",
        dealerLatitude: 32.458113,
        dealerLongitude: -116.9193767,
        colour: "Mauv",
        new: false,
        purchaseDate: new Date("2013-02-28"),
        price: 87311.9,
        topSpeed: 245.1,
    },
    {
        make: "Land Rover",
        model: "Defender",
        gender: "Female",
        buyerAge: 34,
        country: "Indonesia",
        city: "Kedungharjo",
        dealerLatitude: -6.9731701,
        dealerLongitude: 111.7227125,
        colour: "Blue",
        new: true,
        purchaseDate: new Date("2019-02-05"),
        price: 23915.86,
        topSpeed: 244.3,
    },
    {
        make: "Chevrolet",
        model: "Cobalt",
        gender: "Female",
        buyerAge: 41,
        country: "Cuba",
        city: "Yaguajay",
        dealerLatitude: 22.3287394,
        dealerLongitude: -79.2366566,
        colour: "Indigo",
        new: false,
        purchaseDate: new Date("2020-04-29"),
        price: 10789.7,
        topSpeed: 244.3,
    },
    {
        make: "Plymouth",
        model: "Grand Voyager",
        gender: "Male",
        buyerAge: 27,
        country: "Serbia",
        city: "Ljubovija",
        dealerLatitude: 44.1884454,
        dealerLongitude: 19.3776743,
        colour: "Purple",
        new: false,
        purchaseDate: new Date("2016-11-12"),
        price: 84419.26,
        topSpeed: 234.4,
    },
    {
        make: "Chevrolet",
        model: "Suburban 1500",
        gender: "Male",
        buyerAge: 64,
        country: "Russia",
        city: "Stroitel’",
        dealerLatitude: 52.6523079,
        dealerLongitude: 41.4346698,
        colour: "Teal",
        new: true,
        purchaseDate: new Date("2018-10-19"),
        price: 59975.86,
        topSpeed: 181.2,
    },
    {
        make: "Toyota",
        model: "MR2",
        gender: "Male",
        buyerAge: 22,
        country: "Belarus",
        city: "Ros’",
        dealerLatitude: 53.2833165,
        dealerLongitude: 24.4054988,
        colour: "Blue",
        new: false,
        purchaseDate: new Date("2013-02-14"),
        price: 86295.92,
        topSpeed: 175.4,
    },
    {
        make: "Lincoln",
        model: "MKZ",
        gender: "Female",
        buyerAge: 24,
        country: "Greece",
        city: "Pýrgos",
        dealerLatitude: 37.6718487,
        dealerLongitude: 21.4432257,
        colour: "Goldenrod",
        new: false,
        purchaseDate: new Date("2004-03-21"),
        price: 21884.49,
        topSpeed: 177.9,
    },
    {
        make: "Chevrolet",
        model: "Venture",
        gender: "Male",
        buyerAge: 32,
        country: "Indonesia",
        city: "Puteran Kidul",
        dealerLatitude: -7.1239748,
        dealerLongitude: 108.1992015,
        colour: "Violet",
        new: false,
        purchaseDate: new Date("2013-01-29"),
        price: 67379.74,
        topSpeed: 126.5,
    },
    {
        make: "Cadillac",
        model: "STS",
        gender: "Female",
        buyerAge: 24,
        country: "Palestinian Territory",
        city: "Dayr al Ghuşūn",
        dealerLatitude: 32.353463,
        dealerLongitude: 35.074453,
        colour: "Aquamarine",
        new: true,
        purchaseDate: new Date("2013-10-17"),
        price: 21862.85,
        topSpeed: 173.8,
    },
    {
        make: "Acura",
        model: "NSX",
        gender: "Female",
        buyerAge: 28,
        country: "Dominican Republic",
        city: "Hondo Valle",
        dealerLatitude: 18.5049101,
        dealerLongitude: -69.8296974,
        colour: "Puce",
        new: true,
        purchaseDate: new Date("2014-05-06"),
        price: 11660.05,
        topSpeed: 163.9,
    },
    {
        make: "Mercedes-Benz",
        model: "W201",
        gender: "Male",
        buyerAge: 60,
        country: "Brazil",
        city: "Ribeirão Pires",
        dealerLatitude: -23.7130018,
        dealerLongitude: -46.4140801,
        colour: "Red",
        new: true,
        purchaseDate: new Date("2006-10-28"),
        price: 60202.82,
        topSpeed: 221.1,
    },
    {
        make: "Mercedes-Benz",
        model: "R-Class",
        gender: "Male",
        buyerAge: 71,
        country: "Peru",
        city: "Ica",
        dealerLatitude: -14.07546,
        dealerLongitude: -75.7341811,
        colour: "Maroon",
        new: true,
        purchaseDate: new Date("2018-01-10"),
        price: 32143.59,
        topSpeed: 134.3,
    },
    {
        make: "Mercedes-Benz",
        model: "R-Class",
        gender: "Female",
        buyerAge: 66,
        country: "Kazakhstan",
        city: "Zhangaqorghan",
        dealerLatitude: 43.915,
        dealerLongitude: 67.24806,
        colour: "Teal",
        new: false,
        purchaseDate: new Date("2017-10-12"),
        price: 84733.98,
        topSpeed: 244.6,
    },
    {
        make: "Mazda",
        model: "Mazda3",
        gender: "Female",
        buyerAge: 35,
        country: "Taiwan",
        city: "Fengshan",
        dealerLatitude: 22.6113591,
        dealerLongitude: 120.3493158,
        colour: "Violet",
        new: false,
        purchaseDate: new Date("2015-02-27"),
        price: 45129.35,
        topSpeed: 247.8,
    },
    {
        make: "Saab",
        model: "9000",
        gender: "Female",
        buyerAge: 61,
        country: "Argentina",
        city: "Carlos Casares",
        dealerLatitude: -34.7383716,
        dealerLongitude: -58.571838,
        colour: "Goldenrod",
        new: false,
        purchaseDate: new Date("2003-10-13"),
        price: 70345.88,
        topSpeed: 203.1,
    },
    {
        make: "Mazda",
        model: "B-Series",
        gender: "Male",
        buyerAge: 62,
        country: "Philippines",
        city: "Tambilil",
        dealerLatitude: 5.9795827,
        dealerLongitude: 124.6723608,
        colour: "Pink",
        new: false,
        purchaseDate: new Date("2004-12-21"),
        price: 71352.44,
        topSpeed: 183.1,
    },
    {
        make: "Kia",
        model: "Sedona",
        gender: "Male",
        buyerAge: 34,
        country: "Botswana",
        city: "Mopipi",
        dealerLatitude: -21.2001343,
        dealerLongitude: 24.8656498,
        colour: "Yellow",
        new: false,
        purchaseDate: new Date("2006-07-24"),
        price: 87406.81,
        topSpeed: 161.3,
    },
    {
        make: "Hummer",
        model: "H1",
        gender: "Female",
        buyerAge: 24,
        country: "Ethiopia",
        city: "Hīrna",
        dealerLatitude: 9.2185369,
        dealerLongitude: 41.1023814,
        colour: "Pink",
        new: false,
        purchaseDate: new Date("2007-12-12"),
        price: 49829.21,
        topSpeed: 122.7,
    },
    {
        make: "Buick",
        model: "Terraza",
        gender: "Female",
        buyerAge: 42,
        country: "Mexico",
        city: "Benito Juarez",
        dealerLatitude: 19.4102526,
        dealerLongitude: -99.0073673,
        colour: "Maroon",
        new: true,
        purchaseDate: new Date("2002-07-05"),
        price: 25527.2,
        topSpeed: 199.2,
    },
    {
        make: "Chevrolet",
        model: "G-Series G10",
        gender: "Male",
        buyerAge: 44,
        country: "Afghanistan",
        city: "Māymay",
        dealerLatitude: 33.425934,
        dealerLongitude: 66.5344159,
        colour: "Green",
        new: false,
        purchaseDate: new Date("2007-12-16"),
        price: 37730.84,
        topSpeed: 222.4,
    },
    {
        make: "Infiniti",
        model: "EX",
        gender: "Female",
        buyerAge: 61,
        country: "Indonesia",
        city: "Krajan Kedungsalam",
        dealerLatitude: -8.3251,
        dealerLongitude: 112.4501,
        colour: "Turquoise",
        new: false,
        purchaseDate: new Date("2004-09-21"),
        price: 45356.48,
        topSpeed: 139.9,
    },
    {
        make: "Oldsmobile",
        model: "Alero",
        gender: "Male",
        buyerAge: 40,
        country: "Syria",
        city: "Medaya",
        dealerLatitude: 36.3548175,
        dealerLongitude: 36.6980807,
        colour: "Pink",
        new: true,
        purchaseDate: new Date("2009-04-17"),
        price: 65190.08,
        topSpeed: 218.6,
    },
];


// make, model, colour, (city, country), price